# Generated by Django 5.2.6 on 2025-10-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('R&D', 'Research & Development'), ('Sales', 'Sales'), ('Support', 'Customer Support')], max_length=100, unique=True),
        ),
    ]
